# Generated by Django 4.2.3 on 2023-07-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='about_text',
            field=models.TextField(verbose_name='Acerca del Texto'),
        ),
        migrations.AlterField(
            model_name='home',
            name='about_title',
            field=models.CharField(max_length=50, verbose_name='Acerca del Titulo'),
        ),
    ]
